/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Companies;

import Menus.mainmenu;

/**
 *
 * @author Bhasu
 */
public class CompanyMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form CompanyMainMenu
     */
    public CompanyMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Insert_Company = new javax.swing.JButton();
        Delete_Company = new javax.swing.JButton();
        Update_CompanyBtn = new javax.swing.JButton();
        ViewCompanyBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackBtn2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 15));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        Insert_Company.setFont(new java.awt.Font("Lucida Bright", 1, 23)); // NOI18N
        Insert_Company.setForeground(new java.awt.Color(0, 51, 51));
        Insert_Company.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/companies-icon.png"))); // NOI18N
        Insert_Company.setText("Add Company");
        Insert_Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_CompanyActionPerformed(evt);
            }
        });

        Delete_Company.setFont(new java.awt.Font("Lucida Bright", 1, 23)); // NOI18N
        Delete_Company.setForeground(new java.awt.Color(0, 153, 0));
        Delete_Company.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/companies-icon.png"))); // NOI18N
        Delete_Company.setText("Delete Company");
        Delete_Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_CompanyActionPerformed(evt);
            }
        });

        Update_CompanyBtn.setFont(new java.awt.Font("Lucida Bright", 1, 23)); // NOI18N
        Update_CompanyBtn.setForeground(new java.awt.Color(51, 0, 102));
        Update_CompanyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/companies-icon.png"))); // NOI18N
        Update_CompanyBtn.setText("Update Company");
        Update_CompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_CompanyBtnActionPerformed(evt);
            }
        });

        ViewCompanyBtn.setFont(new java.awt.Font("Lucida Bright", 1, 23)); // NOI18N
        ViewCompanyBtn.setForeground(new java.awt.Color(102, 0, 102));
        ViewCompanyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/companies-icon.png"))); // NOI18N
        ViewCompanyBtn.setText("View Companies");
        ViewCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCompanyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewCompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Insert_Company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Update_CompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_Company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewCompanyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_CompanyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert_Company, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Company, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 150, 839, 417);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Company Panel");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 80, 242, 49);

        BackBtn2.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        BackBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/Go-back-icon.png"))); // NOI18N
        BackBtn2.setText("Back");
        BackBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn2);
        BackBtn2.setBounds(1030, 570, 97, 36);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Companies/13983.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 1320, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_CompanyActionPerformed
   InsertCompany im = new InsertCompany();
       
       im.setVisible(true); 
       setVisible(false);
       
// TODO add your handling code here:
    }//GEN-LAST:event_Insert_CompanyActionPerformed

    private void BackBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn2ActionPerformed
    mainmenu ed = new mainmenu();
    ed.setVisible(true);
    setVisible(false);
    
    
   
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn2ActionPerformed

    private void Delete_CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_CompanyActionPerformed
   
        DeleteCompany dc =new DeleteCompany();
        dc.setVisible(true);
        setVisible(false);
    

        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_CompanyActionPerformed

    private void ViewCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCompanyBtnActionPerformed
    ViewCompanies vc = new ViewCompanies();
    vc.setVisible(true);
    setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_ViewCompanyBtnActionPerformed

    private void Update_CompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_CompanyBtnActionPerformed

UpdateCompany ud = new UpdateCompany();
ud.setVisible(true);
setVisible(false);
       

        // TODO add your handling code here:
    }//GEN-LAST:event_Update_CompanyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn2;
    private javax.swing.JButton Delete_Company;
    private javax.swing.JButton Insert_Company;
    private javax.swing.JButton Update_CompanyBtn;
    private javax.swing.JButton ViewCompanyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
